import importlib.util
from pathlib import Path
import unittest

_MODULE_PATH = (
    Path(__file__).resolve().parents[1]
    / "anki_tts_addon"
    / "text_processing.py"
)
_SPEC = importlib.util.spec_from_file_location(
    "text_processing", _MODULE_PATH
)
_MODULE = importlib.util.module_from_spec(_SPEC)
assert _SPEC and _SPEC.loader
_SPEC.loader.exec_module(_MODULE)
extract_speakable_text = _MODULE.extract_speakable_text


EXAMPLE_RAW_CLOZE = (
    "<div>Antigen-<i>independent</i> <u>antibody diversity</u> in "
    "{{c1::<b>light</b>}} <b>chains</b> is generated by "
    "{{c2::<b>VJ</b>}}<b> gene recombination</b></div>"
)


class ExtractSpeakableTextTests(unittest.TestCase):
    def test_question_masks_only_active_second_cloze(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=1)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in light chains is "
                "generated by bla bla bla gene recombination"
            ),
        )

    def test_question_masks_only_active_first_cloze(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=0)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in bla bla bla chains "
                "is generated by VJ gene recombination"
            ),
        )

    def test_question_trusts_rendered_cloze_before_raw_ord(self):
        html = (
            "There is an increased risk for "
            '<span class="cloze">[...]</span> papillary muscle rupture '
            "(post-MI) due to its single blood supply from the "
            "{{c2::posterior descending}} artery"
        )

        result = extract_speakable_text(html, active_ord=1)

        self.assertEqual(
            result,
            (
                "There is an increased risk for bla bla bla papillary "
                "muscle rupture (post-MI) due to its single blood supply "
                "from the posterior descending artery"
            ),
        )

    def test_question_masks_rendered_cloze_span_with_answer_text(self):
        html = (
            "Fructose-1,6-bisphosphate is converted into "
            '<span class="cloze">glyceraldehyde-3-phosphate</span> '
            "and dihydroxyacetone-phosphate via the enzyme aldolase"
        )

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(
            result,
            (
                "Fructose-1,6-bisphosphate is converted into bla bla bla "
                "and dihydroxyacetone-phosphate via the enzyme aldolase"
            ),
        )

    def test_rendered_inactive_cloze_text_remains_speakable(self):
        html = (
            "Ruxolitinib treats "
            '<span class="cloze-inactive">myelofibrosis</span> and '
            '<span class="cloze">[...]</span>'
        )

        result = extract_speakable_text(html, active_ord=1)

        self.assertEqual(
            result,
            "Ruxolitinib treats myelofibrosis and bla bla bla",
        )

    def test_rendered_nested_inactive_cloze_preserves_visible_text(self):
        html = (
            "Ruxolitinib treats "
            '<span class="cloze-inactive">myelofibrosis '
            '<span class="cloze">[...]</span></span>'
        )

        result = extract_speakable_text(html, active_ord=1)

        self.assertEqual(
            result,
            "Ruxolitinib treats myelofibrosis bla bla bla",
        )

    def test_question_without_active_ord_masks_all_raw_clozes(self):
        result = extract_speakable_text(EXAMPLE_RAW_CLOZE, active_ord=None)

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in bla bla bla chains "
                "is generated by bla bla bla gene recombination"
            ),
        )

    def test_literal_bracket_ellipsis_does_not_reveal_active_raw_cloze(self):
        # A bare "[...]" in ordinary content must not flip the masking
        # strategy and unwrap the active raw cloze answer.
        html = "Define the gap: [...] and the value is {{c1::42}}"

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(
            result,
            "Define the gap: bla bla bla and the value is bla bla bla",
        )

    def test_question_masks_active_cloze_span_wrapped_in_other_element(self):
        html = '<div class="front"><span class="cloze">SecretAnswer</span></div>'

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(result, "bla bla bla")

    def test_question_masks_active_cloze_span_with_nested_same_tag(self):
        html = (
            "Start "
            '<span class="cloze">Secret<span>Nested</span>Answer</span>'
            " End"
        )

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(result, "Start bla bla bla End")

    def test_inactive_cloze_sharing_cloze_class_stays_visible(self):
        # Pre-2.1.56 Anki (and some note types) wrap inactive clozes in
        # class="cloze" too; only the active cloze is shown as [...]. The
        # visible inactive text must not be masked.
        html = (
            '<span class="cloze">Giant cell</span> arteritis is a '
            "granulomatous vasculitis that classically involves branches "
            'of the <span class="cloze">[...]</span> carotid artery'
        )

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(
            result,
            (
                "Giant cell arteritis is a granulomatous vasculitis that "
                "classically involves branches of the bla bla bla carotid "
                "artery"
            ),
        )

    def test_inactive_cloze_with_combined_class_stays_visible(self):
        html = (
            '<span class="cloze cloze-inactive">Giant cell</span> arteritis '
            'involves the <span class="cloze">[...]</span> carotid artery'
        )

        result = extract_speakable_text(html, active_ord=0)

        self.assertEqual(
            result,
            "Giant cell arteritis involves the bla bla bla carotid artery",
        )

    def test_answer_side_unwraps_raw_clozes_after_separator(self):
        html = (
            f"<div>front {EXAMPLE_RAW_CLOZE}</div>"
            '<hr id="answer">'
            f"<div>{EXAMPLE_RAW_CLOZE}</div>"
        )

        result = extract_speakable_text(
            html, strip_question=True, active_ord=1
        )

        self.assertEqual(
            result,
            (
                "Antigen-independent antibody diversity in light chains is "
                "generated by VJ gene recombination"
            ),
        )


if __name__ == "__main__":
    unittest.main()
